-- 코드를 입력하세요
SELECT YEAR(O.SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, U.GENDER, COUNT(DISTINCT U.USER_ID) USERS
FROM USER_INFO U
JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
WHERE NOT U.GENDER IS NULL
GROUP BY YEAR(O.SALES_DATE), MONTH(SALES_DATE), U.GENDER
ORDER BY YEAR(O.SALES_DATE), MONTH(SALES_DATE), U.GENDER