-- 코드를 입력하세요
SET @HOUR = -1;
SELECT (@HOUR := @HOUR + 1) HOUR, 
    (SELECT COUNT(HOUR(DATETIME))
    FROM ANIMAL_OUTS
    WHERE HOUR(DATETIME) = @HOUR) COUNT
FROM ANIMAL_OUTS
WHERE @HOUR < 23
GROUP BY HOUR
ORDER BY HOUR