WITH A AS (
    SELECT *
    FROM DEVELOPERS NATURAL JOIN SKILLCODES
    WHERE CODE & SKILL_CODE = CODE
)

select GRADE, ID, EMAIL
FROM (
    SELECT DISTINCT ID, EMAIL,
    CASE WHEN ID IN (
        (SELECT ID FROM A WHERE CATEGORY = 'Front End')
        INTERSECT
        (SELECT ID FROM A WHERE NAME = 'Python')
    ) THEN 'A'
    WHEN ID IN (SELECT ID FROM A WHERE NAME = 'C#') THEN 'B'
    WHEN ID IN (SELECT ID FROM A WHERE CATEGORY = 'Front End') THEN 'C'
    END GRADE
    FROM A
) B
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID